import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About & Safety — MedSafe",
  description:
    "How MedSafe works, its data sources (DDInter 2.0, RxNorm), and its limitations. MedSafe is an educational tool, not a diagnosis.",
};

export default function AboutPage() {
  return (
    <main
      id="main-content"
      className="mx-auto w-full max-w-3xl px-4 py-8 sm:py-10"
    >
      <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">
        About &amp; Safety
      </h1>

      {/* Not-a-diagnosis limitation — front and center */}
      <section
        aria-labelledby="not-diagnosis-heading"
        className="mt-6 rounded-2xl border-2 border-amber-300 bg-amber-50 p-5 sm:p-6"
      >
        <h2
          id="not-diagnosis-heading"
          className="text-xl font-bold text-amber-950"
        >
          This is not a diagnosis
        </h2>
        <p className="mt-2 text-lg leading-relaxed text-amber-950">
          MedSafe is an <strong>educational awareness tool</strong>. It can help
          you spot medication combinations worth asking about — but it does not
          diagnose, treat, or replace professional medical advice. Never start,
          stop, or change a medication based on this tool. Always talk to your
          doctor or pharmacist, and call your local emergency number if you feel
          unwell.
        </p>
      </section>

      {/* How it works */}
      <section aria-labelledby="how-heading" className="mt-8">
        <h2 id="how-heading" className="text-xl font-bold sm:text-2xl">
          How it works
        </h2>
        <ol className="mt-3 list-decimal space-y-2 pl-6 text-lg text-gray-700">
          <li>
            You enter your medications (by typing, or by photographing a label).
          </li>
          <li>
            Each name is standardized to a generic drug via the RxNorm API (so
            brand names like &ldquo;Tylenol&rdquo; map to
            &ldquo;acetaminophen&rdquo;).
          </li>
          <li>
            Every pair of drugs is looked up in the DDInter 2.0 interaction
            database. Only real database matches are shown — nothing is invented.
          </li>
          <li>
            An AI model writes plain-language explanations and a whole-regimen
            summary, and builds an illustrative daily schedule you can export as
            a PDF.
          </li>
        </ol>
      </section>

      {/* Data sources */}
      <section aria-labelledby="sources-heading" className="mt-8">
        <h2 id="sources-heading" className="text-xl font-bold sm:text-2xl">
          Data sources
        </h2>
        <dl className="mt-3 space-y-4 text-gray-700">
          <div>
            <dt className="text-lg font-semibold text-gray-900">DDInter 2.0</dt>
            <dd className="text-base">
              A curated drug–drug interaction database used to determine whether a
              pair of drugs is known to interact and how severe it is (Minor,
              Moderate, or Major). The bulk dataset provides drug pairs and
              severity levels.
            </dd>
          </div>
          <div>
            <dt className="text-lg font-semibold text-gray-900">
              Curated high-risk supplement
            </dt>
            <dd className="text-base">
              A small, hand-vetted set of well-established dangerous combinations
              that DDInter under-covers (for example opioid + benzodiazepine, or
              MAOI + SSRI), based on published sources such as FDA boxed warnings.
              These are clearly labeled and never AI-generated.
            </dd>
          </div>
          <div>
            <dt className="text-lg font-semibold text-gray-900">
              RxNorm (U.S. National Library of Medicine)
            </dt>
            <dd className="text-base">
              A free REST API used to normalize the drug names you enter to a
              standard generic ingredient before any interaction lookup.
            </dd>
          </div>
          <div>
            <dt className="text-lg font-semibold text-gray-900">
              AI explanations
            </dt>
            <dd className="text-base">
              Plain-language explanations and the regimen summary are generated by
              a large language model from the confirmed database results. They are
              worded for general understanding and are not a substitute for
              professional advice.
            </dd>
          </div>
        </dl>
      </section>

      {/* Limitations */}
      <section aria-labelledby="limits-heading" className="mt-8">
        <h2 id="limits-heading" className="text-xl font-bold sm:text-2xl">
          Limitations
        </h2>
        <ul className="mt-3 list-disc space-y-2 pl-6 text-base text-gray-700">
          <li>
            &ldquo;No interaction found&rdquo; means none is in our database — it
            does <strong>not</strong> guarantee a combination is safe.
          </li>
          <li>
            The database covers drug–drug interactions only — not doses,
            allergies, foods, supplements, or your personal medical history.
          </li>
          <li>
            The daily schedule uses generic typical-timing defaults and is
            illustrative only, not a prescription.
          </li>
          <li>
            Drug-name matching and label reading can make mistakes — always review
            what was recognized before relying on it.
          </li>
        </ul>
      </section>

      <p className="mt-10">
        <Link
          href="/"
          className="inline-flex min-h-[44px] items-center rounded-xl bg-blue-600 px-6 py-3 text-lg font-semibold text-white transition hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-300"
        >
          ← Back to the checker
        </Link>
      </p>
    </main>
  );
}
