import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About & Safety — MedSafe",
  description:
    "How MedSafe works, its data sources (DDInter 2.0, RxNorm), and its limitations. MedSafe is an educational tool, not a diagnosis.",
};

export default function AboutPage() {
  return (
    <main id="main-content" className="mx-auto w-full max-w-3xl flex-1 px-6 py-10">
      <h1 className="font-heading text-3xl font-semibold text-ink sm:text-4xl">
        About &amp; safety
      </h1>

      {/* Not-a-diagnosis limitation — front and center */}
      <section
        aria-labelledby="not-diagnosis-heading"
        className="mt-6 rounded-lg border border-line border-l-4 border-l-sev-moderate bg-surface p-6 shadow-card"
      >
        <h2
          id="not-diagnosis-heading"
          className="font-heading text-lg font-semibold text-ink"
        >
          This is not a diagnosis
        </h2>
        <p className="mt-2 leading-relaxed text-body">
          MedSafe is an <strong>educational awareness tool</strong>. It can help
          you spot medication combinations worth asking about — but it does not
          diagnose, treat, or replace professional medical advice. Never start,
          stop, or change a medication based on this tool. Always talk to your
          doctor or pharmacist, and call your local emergency number if you feel
          unwell.
        </p>
      </section>

      {/* How it works */}
      <section aria-labelledby="how-heading" className="mt-10">
        <h2 id="how-heading" className="font-heading text-xl font-semibold text-ink">
          How it works
        </h2>
        <ol className="mt-3 list-decimal space-y-2 pl-6 leading-relaxed text-body marker:text-muted">
          <li>You enter your medications (by typing, or by photographing a label).</li>
          <li>
            Each name is standardized to a generic drug via the RxNorm API (so
            brand names like &ldquo;Tylenol&rdquo; map to
            &ldquo;acetaminophen&rdquo;).
          </li>
          <li>
            Every pair of drugs is looked up in the DDInter 2.0 interaction
            database. Only real database matches are shown — nothing is invented.
          </li>
          <li>
            An AI model writes plain-language explanations and a whole-regimen
            summary, and builds an illustrative daily schedule you can export as a
            PDF.
          </li>
        </ol>
      </section>

      {/* Data sources */}
      <section aria-labelledby="sources-heading" className="mt-10">
        <h2
          id="sources-heading"
          className="font-heading text-xl font-semibold text-ink"
        >
          Data sources
        </h2>
        <dl className="mt-4 space-y-5">
          {[
            {
              term: "DDInter 2.0",
              desc: "A curated drug–drug interaction database used to determine whether a pair of drugs is known to interact and how severe it is (Minor, Moderate, or Major).",
            },
            {
              term: "Curated high-risk supplement",
              desc: "A small, hand-vetted set of well-established dangerous combinations that DDInter under-covers (for example opioid + benzodiazepine, or MAOI + SSRI), based on published sources such as FDA boxed warnings. Clearly labeled and never AI-generated.",
            },
            {
              term: "RxNorm (U.S. National Library of Medicine)",
              desc: "A free REST API used to normalize the drug names you enter to a standard generic ingredient before any interaction lookup.",
            },
            {
              term: "AI explanations",
              desc: "Plain-language explanations and the regimen summary are generated by a large language model from the confirmed database results — worded for general understanding, not a substitute for professional advice.",
            },
          ].map(({ term, desc }) => (
            <div key={term}>
              <dt className="font-medium text-ink">{term}</dt>
              <dd className="mt-1 leading-relaxed text-body">{desc}</dd>
            </div>
          ))}
        </dl>
      </section>

      {/* Limitations */}
      <section aria-labelledby="limits-heading" className="mt-10">
        <h2
          id="limits-heading"
          className="font-heading text-xl font-semibold text-ink"
        >
          Limitations
        </h2>
        <ul className="mt-3 list-disc space-y-2 pl-6 leading-relaxed text-body marker:text-muted">
          <li>
            &ldquo;No interaction found&rdquo; means none is in our database — it
            does <strong>not</strong> guarantee a combination is safe.
          </li>
          <li>
            The database covers drug–drug interactions only — not doses,
            allergies, foods, supplements, or your personal medical history.
          </li>
          <li>
            The daily schedule uses generic typical-timing defaults and is
            illustrative only, not a prescription.
          </li>
          <li>
            Drug-name matching and label reading can make mistakes — always review
            what was recognized before relying on it.
          </li>
        </ul>
      </section>

      <p className="mt-10">
        <Link
          href="/"
          className="inline-block rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-primary-strong"
        >
          ← Back to the checker
        </Link>
      </p>
    </main>
  );
}
