import type { Metadata, Viewport } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "MedSafe — Drug interaction checker",
  description:
    "Educational tool that checks a medication list for drug–drug interactions, builds a daily schedule, and exports a PDF for your doctor. Not medical advice.",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col antialiased">
        {/* Keyboard users can jump straight to the content */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-lg focus:bg-blue-600 focus:px-4 focus:py-2 focus:font-semibold focus:text-white"
        >
          Skip to main content
        </a>

        {/* Primary navigation */}
        <nav aria-label="Primary" className="border-b border-gray-200 bg-white">
          <div className="mx-auto flex max-w-3xl items-center justify-between gap-2 px-4 py-1">
            <Link
              href="/"
              className="inline-flex min-h-[44px] items-center rounded text-lg font-extrabold tracking-tight text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-300"
            >
              ⚕️ MedSafe
            </Link>
            <div className="flex items-center gap-1 text-sm font-semibold sm:gap-2">
              <Link
                href="/"
                className="inline-flex min-h-[44px] items-center rounded px-2 text-gray-700 hover:text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-300"
              >
                Home
              </Link>
              <Link
                href="/about"
                className="inline-flex min-h-[44px] items-center rounded px-2 text-gray-700 hover:text-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-300"
              >
                About
              </Link>
            </div>
          </div>
        </nav>

        {/* Persistent disclaimer banner — on every page */}
        <div
          role="note"
          className="sticky top-0 z-10 bg-amber-100 px-4 py-3 text-center text-sm font-semibold text-amber-950 shadow-sm sm:text-base"
        >
          ⚕️ Educational tool only — not medical advice. Always consult your
          doctor or pharmacist.
        </div>

        {/* Wrapper plays a gentle fade-up each time a page loads. */}
        <div className="animate-fade-up">{children}</div>

        <footer className="mt-auto border-t border-gray-200 bg-gray-50">
          <div className="mx-auto max-w-3xl px-4 py-8 text-sm text-gray-500">
            <p>
              MedSafe is an educational awareness tool, not a diagnosis. Always
              consult your doctor or pharmacist before changing any medication.
            </p>
            <p className="mt-2">
              Interaction data: DDInter 2.0 · Drug names via RxNorm (U.S. National
              Library of Medicine) · Plain-language explanations generated by AI.{" "}
              <Link href="/about" className="font-medium underline">
                About &amp; safety →
              </Link>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
