import type { Metadata } from "next";
import Link from "next/link";
import { Inter, Source_Serif_4 } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});
const heading = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "MedSafe — Drug interaction checker",
  description:
    "Check a medication list for drug–drug interactions, build a daily schedule, and export a summary for your doctor. Educational, not medical advice.",
};

// Small, restrained wordmark: a rounded square with a checkmark (not a cliché
// medical cross, not an emoji).
function Logo() {
  return (
    <span className="inline-flex items-center gap-2">
      <svg
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        aria-hidden="true"
      >
        <rect width="24" height="24" rx="6" fill="var(--primary)" />
        <path
          d="M7 12.5l3 3 7-7"
          stroke="#fff"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
      <span className="font-heading text-lg font-semibold text-ink">
        MedSafe
      </span>
    </span>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${heading.variable}`}>
      <body className="flex min-h-screen flex-col font-sans antialiased">
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:bg-primary focus:px-4 focus:py-2 focus:font-medium focus:text-white"
        >
          Skip to main content
        </a>

        {/* Slim header */}
        <header className="border-b border-line bg-surface">
          <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-3">
            <Link href="/" className="rounded-sm">
              <Logo />
            </Link>
            <nav aria-label="Primary" className="flex gap-6 text-sm font-medium">
              <Link href="/" className="rounded-sm text-body hover:text-primary">
                Home
              </Link>
              <Link
                href="/about"
                className="rounded-sm text-body hover:text-primary"
              >
                About &amp; safety
              </Link>
            </nav>
          </div>
        </header>

        {/* Disclaimer — quiet, persistent, not decorative */}
        <div
          role="note"
          className="border-b border-line bg-primary-tint text-primary-strong"
        >
          <div className="mx-auto max-w-4xl px-6 py-2 text-center text-sm">
            Educational tool only — not medical advice. Always consult your
            doctor or pharmacist.
          </div>
        </div>

        {children}

        <footer className="mt-auto border-t border-line bg-surface">
          <div className="mx-auto max-w-4xl px-6 py-8 text-sm text-muted">
            <p>
              MedSafe is an educational awareness tool, not a diagnosis. Always
              consult your doctor or pharmacist before changing any medication.
            </p>
            <p className="mt-2">
              Interaction data: DDInter 2.0 &amp; a curated high-risk supplement ·
              Drug names via RxNorm (U.S. National Library of Medicine) ·
              Plain-language explanations generated by AI.{" "}
              <Link href="/about" className="font-medium text-primary underline">
                About &amp; safety
              </Link>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
